[env]
CMAKE_POLICY_VERSION_MINIMUM = "3.5"
CMAKE_TOOLCHAIN_FILE_aarch64_apple_ios = { value = "crates/ducad-kernel/ios/ios-toolchain.cmake", relative = true }
CMAKE_TOOLCHAIN_FILE_aarch64_apple_ios_sim = { value = "crates/ducad-kernel/ios/ios-toolchain.cmake", relative = true }
