[package]
name = "cadraw-io"
version.workspace = true
edition.workspace = true
license.workspace = true
authors.workspace = true

[dependencies]
cadraw-core = { workspace = true }
cadraw-sketch = { workspace = true }
cadraw-kernel = { workspace = true }
glam = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
anyhow = { workspace = true }
