[package]
name = "ducad-ui"
version.workspace = true
edition.workspace = true
license.workspace = true
authors.workspace = true

[dependencies]
ducad-core = { workspace = true }
ducad-kernel = { workspace = true }
ducad-io = { workspace = true }
ducad-i18n = { workspace = true }
egui = { workspace = true }
glam = { workspace = true }
egui_material_icons = { workspace = true }
